"""empty message

Revision ID: 51f9cd912d88
Revises: 6e75984f98fe
Create Date: 2023-08-22 11:44:37.260393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f9cd912d88'
down_revision = '6e75984f98fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_password_hash'), 'user', ['password_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_hash'), table_name='user')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
